version: '3.9'

services:
  app:
    image: olegkuro/skypro-hw:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:80
    volumes:
      - ./data:/code/data
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network: